### ISSUE TITLE
Did you abandon this project in preference to https://github.com/fukamachi/qlot?

### ISSUE THREAD

**Issue by svetlyak40wt** [daewok/ql-scm#1]

**Comment by svetlyak40wt** [comment]
@daewok can you answer, please?

**Comment by daewok** [comment]
Sorry, I somehow missed this when you opened it!

I have mostly abandoned it, but not in favor of qlot. I'm working on a separate package manager that does not use the quicklisp client, but can use quicklisp derived distribution metadata. Once that's solid (actually nearly there - I'm using it as my daily driver, but I know how to deal with all the remaining quirks =P), I'll be layering in the ability to take additional metadata (such as upstream git repos for projects) and allow the repos to be cloned locally, hopefully while including an editable option!

The primary test case for this is currently my research group. We have a bunch of CL repos that aren't public, but are hosted on a publicly accessible server due to our university environment. So I'll still fix bugs and such in ql-scm since I've got people using it on a ~daily basis, but I don't see myself adding any new features.

**Comment by svetlyak40wt** [comment]
Interesting! Could you share a link to this new package manager?

**Comment by daewok** [comment]
Sure thing: https://gitlab.common-lisp.net/clpm/clpm

Now that my semester is over, I'm hoping to get it into good shape over the next month or so.

**Comment by svetlyak40wt** [comment]
Great, thank you! Will try clpm soon.

**Comment by svetlyak40wt** [comment]
BTW, why it is hosted not at the GitHub?
